version: '3.7'
services:
    postgres:
        image: postgres:14-alpine3.17
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        ports:
          - '5432:5432'
        volumes: 
          - ./postgres-data:/var/lib/postgresql/data
          # copy the sql script to create tables
          - ./sqls/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
