name: CICD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Run unit tests
        run: |
          echo "Finish CI test"

  CD-dev:
    name: Deploy to Fly.io develop
    needs: CI
    environment: beta
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: |
          flyctl deploy --config fly.toml --remote-only -e \
          BOT_TOKEN=${{ secrets.BOT_TOKEN }},\
          DB_HOST=${{ secrets.DB_HOST }},\
          DB_NAME=${{ secrets.DB_NAME }},\
          DB_PASSWORD=${{ secrets.DB_PASSWORD }},\
          DB_PORT=${{ secrets.DB_PORT }},\
          DB_USER=${{ secrets.DB_USER }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      - run: echo "Deploy to fly develop"