name: tests

on:
  push:
    branches:
      - main
      - feature/study_github_action_with_flyio


jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run unit tests
        run: |
          echo "hello world"
